### ISSUE TITLE
Commas Considered Harmful

### ISSUE THREAD

**Issue by ashlinharris** [bailey-lab/MIPTools#20]
### Bug Description

The pipeline produces sample sheets associated with wrangler files, and these might ~~contain commas The analysis notebooks misreads these files and reports that 0 haplotypes have been found.~~ have missing values or contain quotation marks. This can cause errors further in the pipeline, so researchers will manually edit entries with commas to avoid the issue.

### Expected Behavior

Ideally, any output from one tools should be accepted as input to the next without need for modification. For now, it may be sufficient to include a warning in the analysis notebooks, since the error message downstream doesn't indicate the cause of the issue. 

### Reprex

I was not able to replicate this exact issue, but several researchers have experienced a problem here.

```shell
# insert reprex here
```
-->

**Comment by aydemiro** [comment]
I'm closing this as there is no specific bug or example. We can work on it when a specific issue arise.
