### ISSUE TITLE
Arguments with spaces cause errors

### ISSUE THREAD

**Issue by arisp99** [bailey-lab/MIPTools#26]
### Bug Description

When arguments contain spaces, `argparse` is unable to parse the spaces and causes our code to crash. I encountered this error when attempting to run through the [analysis test run](https://docs.google.com/document/d/1nbJg417Wy_fRjZmMltGPVI73rjbjIwNh0dXDwRkt-1E/). When running through the first section of the tutorial, the user is asked to specify the probe sets used before running the wrangler app. In the example, we write

```shell
probe_sets_used="DR1,VAR4"
```

However, if the user adds a space in between these two probe sets:

```shell
probe_sets_used="DR1, VAR4"
```

and tries to run the wrangler app using the following:

```shell
singularity run --app wrangler \
    -B $project_resources:/opt/project_resources \
    -B $fastq_dir:/opt/data \
    -B $wrangler_dir:/opt/analysis \
    $miptools -p $probe_sets_used -s $sample_sets_used -e $experiment_id \
    -l  $sample_list -c $cpu_number -m $min_capture_length
```

the app will fail with the following error: `generate_wrangler_scripts.py: error: unrecognized arguments: VAR4`.

Our code does aim to deal with these cases by cleaning up spaces in the following lines:

https://github.com/bailey-lab/MIPTools/blob/09f52eff8059661f04962e24715b3a1ad83d47cc/src/generate_wrangler_scripts.py#L79-L96

However, the code fails before we are able to reach this stage. It seems that the error is triggered by `argparse` here: https://github.com/bailey-lab/MIPTools/blob/09f52eff8059661f04962e24715b3a1ad83d47cc/src/generate_wrangler_scripts.py#L68

### Suggested Implementation

Seeing as we are unable to deal with spaces within the python file, I suggest we deal with any spaces and misformatted arguments within the wrangler app before feeding in our arguments to the python script. We can do simple string manipulation in bash as outlined [here](https://tldp.org/LDP/abs/html/string-manipulation.html). For instance, to remove whitespace:

```shell
probe_sets_used="DR1, VAR4"
echo bash ${probe_sets_used// /}
#> DR1,VAR4
```

**Comment by aydemiro** [comment]
yes we can change the app code to:
`probe_sets_used=${probe_sets_used// /}
sample_sets_used=${sample_sets_used// /}
singularity run --app wrangler ...`
