### ISSUE TITLE
Update muscle multiple sequence alignment program

### ISSUE THREAD

**Issue by arisp99** [bailey-lab/MIPTools#35]
The [MUSCLE multiple sequence alignment program](https://drive5.com/muscle5/manual/about_muscle5.html) underwent a major improvement to version 5 in late 2021. The authors state that:
> Muscle v5 is much more accurate, is often faster, and scales to much larger datasets.

Given these improvements, we should upgrade the current [binary](https://github.com/bailey-lab/MIPTools/blob/master/bin/muscle) included in MIPTools.

**Comment by arisp99** [comment]
This issue might be something @aydemiro can provide feedback for. I am not sure at which stage we actually use the muscle program for sequence alignment. It is defined in several template settings files. For example, we define it here:

https://github.com/bailey-lab/MIPTools/blob/dea84f8509832b70c0546ea1639837385cf4665b/base_resources/templates/analysis_settings_templates/settings.txt#L12-L13

Where is this alignment program used?

---

An additional consideration is that given that change in major version, the program is likely to not be backward compatible so we may need to change some internals that call muscle.

Basic usage for v5:

```shell
muscle -align sequences.fasta -output alignment.fasta
```

Basic usage for v3 (current version):

```shell
muscle -in <inputfile> -out <outputfile>
```

**Comment by aydemiro** [comment]
@arisp99 I don't think we are actively using Muscle in MIPTools. It is used in process_contig function which is also not used. Both can be removed from the next release.

**Comment by arisp99** [comment]
Thanks, @aydemiro for the clarification. Does this mean that we do not use the `multipleSequenceAligner` setting at all? Some settings files use `decipher` instead of `muscle`. Is it safe to remove those lines of code as well?

A quick example:
https://github.com/bailey-lab/MIPTools/blob/b4ad24dcae0979f0a1679781d8bd0b785fe5b3aa/base_resources/templates/analysis_settings_templates/hg38_settings.txt#L12-L13

**Comment by aydemiro** [comment]
Correct. multipleSequenceAligner is not used and can be removed from the settings file. And we are not using any of the setting files from the templates other than the settings.txt file. So those files can also be removed.

**Comment by arisp99** [comment]
It appears that we additionally no longer need the `msa2vcf` program. This seems to have been used in `process_contig()` function. If this is the case, then we can remove the program and remove the `msa_to_vcf.py` file (https://github.com/bailey-lab/MIPTools/blob/c4001d235c5e616a814912bd457da5f59eb2e280/src/msa_to_vcf.py).

Can you confirm @aydemiro?

**Comment by aydemiro** [comment]
I can confirm that msa2vcf is also not needed anymore.
