### ISSUE TITLE
Unable to find C and C++ compilers during build

### ISSUE THREAD

**Issue by arisp99** [bailey-lab/MIPTools#43]
### Bug Description

When attempting to build MIPTools, we are unable to build the [elucidator](https://github.com/nickjhathaway/elucidator) program. The build process crashes with an error message indicating that the C and C++ compilers were not found. This is most likely due to https://github.com/nickjhathaway/elucidator/commit/9bcfe9cc5dc2752420a8a4312216b15f100af069, where the compiler versions were upgraded. Now, `gcc-10` (the C compiler) and `g++-10` (the C++ compiler) are required.

The MIPTools container is built on Ubuntu 20.04. We install GCC via `apt-get` and g++ via `anaconda`. However, for Ubuntu 20.04, the default version of GCC/g++ seems to be `gcc-9`/`g++-9`. To fix, this bug, we likely need to specify the installation of GCC/g++ version 10.

### Steps to Reproduce

1. Build the development container

**Comment by JeffAndBailey** [comment]
Or we may need to move to 22.04.....   although may be a big lift.

**Comment by arisp99** [comment]
Yes, we could consider moving to 22.04 at a later point. It is not needed yet, however, as I managed to fix this by upgrading to gcc-10/g++-10.
